swagger: '2.0'
info:
  version: 1.0.0
  title: Node with Docker
  license:
    name: Proprietary
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
paths:
  '/swagger.json': 
    get:
      tags:
        - Spec
      # operationID: retrieveSpec
      description: Retrieve OpenAPI spec.
      responses:
        '200':
          description: Successful
          schema:
            type: object
  '/register':
    post:
      description: Admin registers a new user
      # operationID: adminRegisterUser
      tags:
        - Register
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserRegisterBase'
      responses:
        '200':
          description: User registered
          schema:
            type: object
        '400':
          description: Bad Request
          schema:
            type: object
        default:
          description: Unexpected error
          schema:
            type: object    
  '/user/{email}': 
    get:
      description: Get a user
      # operationID: getUser
      tags:
        - Get a user
      parameters:
        - $ref: '#/parameters/email'
      responses:
        '200':
          description: User details queried
          schema:
            type: object
        '400':
          description: Bad Request
          schema:
            type: object
        default:
          description: Unexpected error
          schema:
            type: object
definitions:
  UserRegisterBase:
    required:
      - name
      - address
      - password
      - email
    type: object
    properties:
      name:
        type: string
      address:
        type: string
      password:
        type: string 
      email:
        type: string   

parameters:
  email:
    name: email
    in: path
    required: true
    type: string


