version: '3.1'

services:
  wordpress:
    image: wordpress
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wpdbpasswd
      WORDPRESS_DB_USER: wpdbuser
      WORDPRESS_DB_NAME: wpdb
    restart: always

  db:
    image: mariadb:10.4-bionic
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpasswd
    volumes:
      - "./volumes/db:/var/lib/mysql"
    restart: always