swagger: '2.0'
info:
  version: 1.0.0
  title: Node Server
  license:
    name: Proprietary
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https

paths:
  '/swagger.json': 
  get:
    tags:
      -Spec
    operationID: retrieveSpec
    description: Retrieve OpenAPIS spec.
    responses:
    '200':
      description: Successful
      schema:
        type: object
  '/user/{email}': 
    get:
      description: Get user
      operationID: getUser
      tags:
        - Register
      parameters:
        - $ref: '#/parameters/email'
      responses:
        '200':
          description: Successful
          schema:
            type: object
        '400':
          description: Bad Request
          schema:
            type: object
        default:
          description: Unexpected error
          schema:
            type: object
parameters:
  email:
    name: email
    in: path
    required: true
    type: string

