version: '3.1'

services:
  wordpress:
    image: wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpdbpasswd
      WORDPRESS_DB_NAME: wpdb
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpdbpasswd
      MYSQL_DATABASE: wpdb
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./volumes/db:/var/lib/mysql"
    restart: always