version: "3"

services:

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    volumes:
      - ./service1:/app
    ports:
      - 3000:3000
    restart: always

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    volumes:
      - ./service2:/app
    ports:
      - 5000:5000
    restart: always  

  postgresdb:
    image: postgres:10.7-alpine
    restart: always

volumes:
  conf-data:

  