version: '2'

services:
  a:
    image: tutum/hello-world
    container_name: foo
    networks: 
    - superbridge
    networks:
      frontend:
        aliases: 
          - web # shared alias with b
    external_links:
      - helloworld1:h1
  b:
    image: tutum/hello-world
    networks:
      frontend:
        aliases: 
          - web  
      backend:
        aliases: 
          - website
  c: 
    image: tutum/hello-world
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  superbridge:
    external: true

  # default:
  #   driver: bridge